### ISSUE TITLE
What different between this firmware and klever1988 firmware?

### ISSUE THREAD

**Issue by lessload** [jayanta525/openwrt-nanopi-r2s#11]
I saw some firmware from https://github.com/klever1988/nanopi-openwrt
Is it the same ?

**Comment by jayanta525** [comment]
No @lessload .The firmware you have linked is not the same.

This repo is based on friendlywrt kernel, but with mainline OpenWrt. I tried to keep the kernel sources as close to the vendor's kernel to provide maximum compatibility such that users can use this instead of FriendlyWrt which IMO was bloated with unnecessary packages.

As this board is now merged into mainline OpenWrt, the repo is no longer maintained.
