### ISSUE TITLE
Add PWM FAN function on R2S

### ISSUE THREAD

**Issue by CWZ7605** [jayanta525/openwrt-nanopi-r2s#6]
I want to connect the fan interface on the R2S motherboard.
But I don't want the fan to keep running at full speed, so I need it to control the fan speed through PWM output.

This is the OFFICIAL firmware PWM control function, I hope to help you.
https://github.com/friendlyarm/friendlywrt/commit/e1fb88ff29bcf634c875b94a9026565c7780149f

Well, if there is anything I can do to help, let me know.

**Comment by jayanta525** [comment]
Hello @CWZ7605 

This repository was prepared keeping in mind to create a PR at openwrt/master. 
Since, an RK3328 target (Pine64 Rock64) is already pending, its better to wait to avoid conflicts in merge situations.

For adding additional functionality to R2S, I have created circleci branch here: [link](https://github.com/jayanta525/openwrt-nanopi-r2s/tree/circleci) 
which already includes the irq_optimize [procd script](https://github.com/jayanta525/openwrt-nanopi-r2s/tree/circleci/files), and creates images with circleci.

I don't have a pwm capable fan, but i will try to modify the script from the commit [at friendlywrt](https://github.com/friendlyarm/friendlywrt/commit/e1fb88ff29bcf634c875b94a9026565c7780149f) and test with an multimeter.

Please keep an eye at the circleci branch for this feature.

**Comment by CWZ7605** [comment]
> 
> 
> Hello @CWZ7605
> 
> This repository was prepared keeping in mind to create a PR at openwrt/master.
> Since, an RK3328 target (Pine64 Rock64) is already pending, its better to wait to avoid conflicts in merge situations.
> 
> For adding additional functionality to R2S, I have created circleci branch here: [link](https://github.com/jayanta525/openwrt-nanopi-r2s/tree/circleci)
> which already includes the irq_optimize [procd script](https://github.com/jayanta525/openwrt-nanopi-r2s/tree/circleci/files), and creates images with circleci.
> 
> I don't have a pwm capable fan, but i will try to modify the script from the commit [at friendlywrt](https://github.com/friendlyarm/friendlywrt/commit/e1fb88ff29bcf634c875b94a9026565c7780149f) and test with an multimeter.
> 
> Please keep an eye at the circleci branch for this feature.

Thanks for your help
